### ISSUE TITLE
Incorrect timezone handling when creating appointments - local time not preserved

### ISSUE THREAD

**Issue by gabovj** [DMJoh/Mediqux#14]
Describe the bug
Timezone conversion issue when creating appointments. The system incorrectly displays appointment times by converting local time to a different timezone. When creating an appointment at 12:00 PM local time (GMT-5, Cancún, Mexico), the system displays it as 7:00 PM.
To Reproduce

Go to 'Appointments' section
Click on 'Create New Appointment' or similar button
Set appointment time to '12:00 PM' (noon) local time
Save the appointment
View the created appointment - it displays as '7:00 PM' instead of '12:00 PM'

Expected behavior
The appointment should display the same time that was entered (12:00 PM local time). The system should either:

Store and display times in local timezone, or
Properly handle timezone conversion to show the correct local time to the user

Desktop (please complete the following information):

OS: Fedora Linux
Browser: Chrome
Version: Version 140.0.7339.80 

Additional context

Location: Cancún, Quintana Roo, Mexico (GMT-5)
Deployment: Using Docker Compose (latest version from main branch)
Time difference observed: 7 hours ahead (12:00 PM → 7:00 PM), suggesting possible UTC conversion issue
System timezone: The server container might be defaulting to UTC while the frontend is in local time, causing the 5-hour difference to become 7 hours due to improper handling

Suggestion: The application might need to implement proper timezone handling, either by:

Storing times with timezone information
Using the browser's local timezone for display
Adding a timezone configuration setting for users

**Comment by DMJoh** [comment]
Issue fixed in #16.

To apply the fix, please pull the latest image and restart the Docker Compose stack:

```bash
docker compose pull
docker compose up -d
```
After that, try editing or re-adding appointments to verify the issue is resolved.

**Comment by tayyoungblood** [comment]
The issue is still unresolved when displaying patient's date of birth. When h the date of birth is entered and saved, the list displays the day prior to the date entered. Note: when editing the patient's record, the correct date of birth is shown.

**Comment by DMJoh** [comment]
Thanks for reporting back.

Issue Confirmed: You're absolutely right - this was a timezone conversion bug affecting users in negative timezones (GMT-5, GMT-8, etc.). When you entered a date like "May 15, 1990",

Fixed in v1.0.5:

The fix has been tested and verified to work correctly for users in GMT-5, GMT+5:30, and other timezones. Can you take a look at this from your side after deploying the new images and report back. Thanks

**Comment by tayyoungblood** [comment]
I have pulled the latest docker images. Unfortunately, the issue persists. I am in UTC-5 and the list still shows a DOB the day prior (the 19th versus the 20th). Thanks for your hard work on this.

**Comment by DMJoh** [comment]
"I have tested this with UTC-5 and it is working as expected. Can you please make sure you do the following:

1. Pull the latest image (which you may have already done).
2. Clear your browser cache completely or test in an incognito/private browser window (preferred).

If this doesn't work, can you let me know the exact steps that you are following so that I can reproduce it on my end?"

**Comment by tayyoungblood** [comment]
Yep. It was the cache. It's always the cache. I appreciate the work you have put in. For formality's sake, I can confirm this issue has been fixed.

**Comment by DMJoh** [comment]
Thanks for confirming. Thanks to you too for taking an effort and looking in to the issues.
